embedding_model = "text-embedding-3-large"
CSV_PATH = "data/wiki_movie_plots_deduped.csv"
CHROMA_DB_DIR = "./chroma_db"
COLLECTION_NAME = "movie_plots"
CHUNK_SIZE = 300  # words per chunk
SUBSET_SIZE = 300
top_k = 5
openai_llm = "gpt-5"
prompt_dir= "utils/prompt_templates/step_01"